apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: react-app
spec:
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react
        image: 
        resources:
          limits:
            memory: "100Mi"
            cpu: "80m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  selector:
    app: react-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
